# Generated by Django 2.2.4 on 2019-08-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatesRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('ibm_classification', models.CharField(blank=True, max_length=100)),
                ('user_agrees_with_classification', models.BooleanField(blank=True)),
            ],
        ),
    ]
